name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools python3-wheel git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev

      - name: Instalar Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython

      - name: Gerar APK
        run: |
          buildozer android debug

      - name: Enviar APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: SISTEMA-EXPRESS-APK
          path: bin/*.apk
